// <auto-generated />
using Cysharp.Threading.Tasks;
using GameDeveloperKit.UI;

[UIOption("Resources/Loading", 300)]
public sealed partial class LoadingWindow
{
    private global::UnityEngine.UI.Slider slider_slider;
    private global::TMPro.TextMeshProUGUI text_info;
    private global::UnityEngine.UI.RawImage img_video;

    private UniTask InitializeDesignAsync()
    {
        slider_slider = Document.GetComponent<global::UnityEngine.UI.Slider>("b_Slider");
        text_info = Document.GetComponent<global::TMPro.TextMeshProUGUI>("b_info");
        img_video = Document.GetComponent<global::UnityEngine.UI.RawImage>("b_video");
        return UniTask.CompletedTask;
    }

    private void ReleaseDesign()
    {
        slider_slider = null;
        text_info = null;
        img_video = null;
    }
}
