// <auto-generated />
// Tips 模态提示弹窗绑定（GDK 代码侧）。
// prefab 由客户端提供，路径为客户端 Bundles 下的 UI_ConfirmPopup.prefab。
// 客户端 prefab 结构约定（绑定 key）：
//   - UIDocument 组件（必选）
//   - Panel : Transform — 弹窗容器（打开/关闭缩放动画作用对象）
//   - b_text_title : TextMeshProUGUI — 弹窗标题
//   - b_text_content : TextMeshProUGUI — 提示文本
//   - b_btn_confirm : Button — 确认按钮
//   - b_text_confirm : TextMeshProUGUI — 确认按钮文案
//   - b_btn_cancel : Button — 取消按钮（无取消模式时自动隐藏）
//   - b_text_cancel : TextMeshProUGUI — 取消按钮文案
//   - b_text_countdown : TextMeshProUGUI — 自动确认倒计时文本（可选，无自动确认时自动隐藏）
using Cysharp.Threading.Tasks;
using GameDeveloperKit.UI;

[UIOption("Assets/Bundles/UI/Common/Popup/UI_ConfirmPopup.prefab", 400 /* UILayer.Message */)]
public sealed partial class TipsWindow
{
    private global::TMPro.TextMeshProUGUI text_title;
    private global::TMPro.TextMeshProUGUI text_content;
    private global::UnityEngine.UI.Button btn_confirm;
    private global::TMPro.TextMeshProUGUI text_confirm;
    private global::UnityEngine.UI.Button btn_cancel;
    private global::TMPro.TextMeshProUGUI text_cancel;
    private global::TMPro.TextMeshProUGUI text_countdown;

    private UniTask InitializeDesignAsync()
    {
        text_title = Document.GetComponent<global::TMPro.TextMeshProUGUI>("b_text_title");
        text_content = Document.GetComponent<global::TMPro.TextMeshProUGUI>("b_text_content");
        btn_confirm = Document.GetComponent<global::UnityEngine.UI.Button>("b_btn_confirm");
        text_confirm = Document.GetComponent<global::TMPro.TextMeshProUGUI>("b_text_confirm");
        btn_cancel = Document.GetComponent<global::UnityEngine.UI.Button>("b_btn_cancel");
        text_cancel = Document.GetComponent<global::TMPro.TextMeshProUGUI>("b_text_cancel");
        text_countdown = Document.GetComponent<global::TMPro.TextMeshProUGUI>("b_text_countdown");
        return UniTask.CompletedTask;
    }

    private void ReleaseDesign()
    {
        text_title = null;
        text_content = null;
        btn_confirm = null;
        text_confirm = null;
        btn_cancel = null;
        text_cancel = null;
        text_countdown = null;
    }
}
