// <auto-generated />
using Cysharp.Threading.Tasks;
using GameDeveloperKit;

public static partial class TestModule
{
    public static UniTask<TestWindow> OpenAsync()
    {
        return App.UI.OpenAsync<TestWindow>();
    }

    public static void Close()
    {
        App.UI.Close<TestWindow>();
    }
}
