// <auto-generated />

public sealed class TestModel
{
    public global::UnityEngine.UI.Text text_text;
    public global::TMPro.TextMeshProUGUI text_t2;
    public global::UnityEngine.UI.Image img_image;
    public global::UnityEngine.UI.Button btn_bu;
    public global::UnityEngine.UI.Image img_bu;
}
