// <auto-generated />
using Cysharp.Threading.Tasks;
using GameDeveloperKit;
using GameDeveloperKit.Localization;
using GameDeveloperKit.UI;

[UIOption("Assets/GameDeveloperKit/Simples/UI/Test.prefab", UILayer.Window)]
public sealed partial class TestWindow : UIWindow
{
    private readonly TestController m_Controller = new TestController();
    private bool m_LocalizationSubscribed;

    public TestModel Model { get; private set; }

    public override async UniTask OnAwakeAsync()
    {
        Model = new TestModel();
        Model.text_text = Document.GetComponent<global::UnityEngine.UI.Text>("b_text");
        Model.text_t2 = Document.GetComponent<global::TMPro.TextMeshProUGUI>("b_t2");
        Model.img_image = Document.GetComponent<global::UnityEngine.UI.Image>("b_Image");
        Model.btn_bu = Document.GetComponent<global::UnityEngine.UI.Button>("b_bu");
        Model.img_bu = Document.GetComponent<global::UnityEngine.UI.Image>("b_bu");

        SubscribeLocalization();
        RefreshLocalization();
        await m_Controller.OnAwakeAsync(this, Model);
    }

    private void SubscribeLocalization()
    {
        if (m_LocalizationSubscribed)
        {
            return;
        }

        App.Localization.LocaleChanged += OnLocaleChanged;
        m_LocalizationSubscribed = true;
    }

    private void UnsubscribeLocalization()
    {
        if (m_LocalizationSubscribed && App.TryGetRegistered<LocalizationModule>(out var localization))
        {
            localization.LocaleChanged -= OnLocaleChanged;
        }

        m_LocalizationSubscribed = false;
    }

    private void OnLocaleChanged(LocalizationChangedEventArgs args)
    {
        RefreshLocalization();
    }

    private void RefreshLocalization()
    {
        Model.text_t2.text = App.Localization.GetText("ui.start");
        Model.text_text.text = App.Localization.GetText("ui.text.text");
    }

    public override UniTask OnOpenAsync()
    {
        return m_Controller.OnOpenAsync(this);
    }

    public override void OnEnable()
    {
        m_Controller.OnEnable(this);
    }

    public override void OnDisable()
    {
        m_Controller.OnDisable(this);
    }

    public override void Release()
    {
        UnsubscribeLocalization();
        m_Controller.Release(this);
        Model = null;
        base.Release();
    }
}
