using System;
using System.Collections.Generic;
using System.Text;
using GameDeveloperKit.UI;

namespace GameDeveloperKit.UIEditor
{
    internal static partial class UIDocumentGenerator
    {
        private static string GenerateLogic(string windowName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            sb.AppendLine("using GameDeveloperKit.UI;");
            sb.AppendLine();
            sb.AppendLine("public sealed partial class " + windowName + " : UIWindow");
            sb.AppendLine("{");
            sb.AppendLine("    public override async UniTask OnAwakeAsync()");
            sb.AppendLine("    {");
            sb.AppendLine("        await InitializeDesignAsync();");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public override UniTask OnOpenAsync()");
            sb.AppendLine("    {");
            sb.AppendLine("        return UniTask.CompletedTask;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public override void Release()");
            sb.AppendLine("    {");
            sb.AppendLine("        ReleaseDesign();");
            sb.AppendLine("        base.Release();");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GenerateDesign(
            string windowName,
            string uiPath,
            UILayer layer,
            List<BindingInfo> bindings,
            List<LocalizedTextBindingInfo> localizedTextBindings)
        {
            if (localizedTextBindings == null)
            {
                throw new ArgumentNullException(nameof(localizedTextBindings));
            }

            var hasLocalizedTexts = localizedTextBindings.Count > 0;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using Cysharp.Threading.Tasks;");
            if (hasLocalizedTexts)
            {
                sb.AppendLine("using GameDeveloperKit;");
                sb.AppendLine("using GameDeveloperKit.Localization;");
            }

            sb.AppendLine("using GameDeveloperKit.UI;");
            sb.AppendLine();
            sb.AppendLine("[UIOption(" + Quote(uiPath) + ", " + layer.Order + " /* UILayer." + layer + " */)]");
            sb.AppendLine("public sealed partial class " + windowName);
            sb.AppendLine("{");
            if (hasLocalizedTexts)
            {
                sb.AppendLine("    private bool m_LocalizationSubscribed;");
                sb.AppendLine();
            }

            foreach (var binding in bindings)
            {
                sb.AppendLine("    private " + binding.ComponentType + " " + binding.FieldName + ";");
            }

            if (bindings.Count > 0)
            {
                sb.AppendLine();
            }

            sb.AppendLine("    private UniTask InitializeDesignAsync()");
            sb.AppendLine("    {");
            foreach (var binding in bindings)
            {
                sb.AppendLine("        " + binding.FieldName + " = Document.GetComponent<" + binding.ComponentType + ">(" + Quote(binding.MappingName) + ");");
            }

            if (hasLocalizedTexts && bindings.Count > 0)
            {
                sb.AppendLine();
            }

            if (hasLocalizedTexts)
            {
                sb.AppendLine("        SubscribeLocalization();");
                sb.AppendLine("        RefreshLocalization();");
            }

            sb.AppendLine("        return UniTask.CompletedTask;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private void ReleaseDesign()");
            sb.AppendLine("    {");
            if (hasLocalizedTexts)
            {
                sb.AppendLine("        UnsubscribeLocalization();");
            }

            if (hasLocalizedTexts && bindings.Count > 0)
            {
                sb.AppendLine();
            }

            foreach (var binding in bindings)
            {
                sb.AppendLine("        " + binding.FieldName + " = null;");
            }

            sb.AppendLine("    }");
            if (hasLocalizedTexts)
            {
                sb.AppendLine();
                sb.AppendLine("    private void SubscribeLocalization()");
                sb.AppendLine("    {");
                sb.AppendLine("        if (m_LocalizationSubscribed)");
                sb.AppendLine("        {");
                sb.AppendLine("            return;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        App.Localization.LocaleChanged += OnLocaleChanged;");
                sb.AppendLine("        m_LocalizationSubscribed = true;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    private void UnsubscribeLocalization()");
                sb.AppendLine("    {");
                sb.AppendLine("        if (m_LocalizationSubscribed && App.TryGetRegistered<LocalizationModule>(out var localization))");
                sb.AppendLine("        {");
                sb.AppendLine("            localization.LocaleChanged -= OnLocaleChanged;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        m_LocalizationSubscribed = false;");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    private void OnLocaleChanged(LocalizationChangedEventArgs args)");
                sb.AppendLine("    {");
                sb.AppendLine("        RefreshLocalization();");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine("    private void RefreshLocalization()");
                sb.AppendLine("    {");
                foreach (var localizedTextBinding in localizedTextBindings)
                {
                    sb.AppendLine("        " + localizedTextBinding.FieldName + ".text = App.Localization.GetText(" + Quote(localizedTextBinding.Key) + ");");
                }

                sb.AppendLine("    }");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GenerateModel(string windowName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();
            sb.AppendLine("public sealed partial class " + windowName);
            sb.AppendLine("{");
            sb.AppendLine("    public sealed class Model");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
