// <auto-generated />
using Cysharp.Threading.Tasks;
using GameDeveloperKit;

public static partial class LoadingModule
{
    public static UniTask<LoadingWindow> OpenAsync()
    {
        return App.UI.OpenAsync<LoadingWindow>();
    }

    public static void Close()
    {
        App.UI.Close<LoadingWindow>();
    }
}
