// <auto-generated />
using Cysharp.Threading.Tasks;
using GameDeveloperKit.UI;

[UIOption("Assets/GameDeveloperKit/Simples/UI/Loading.prefab", UILayer.Window)]
public sealed partial class LoadingWindow : UIWindow
{
    private readonly LoadingController m_Controller = new LoadingController();

    public LoadingModel Model { get; private set; }

    public override async UniTask OnAwakeAsync()
    {
        Model = new LoadingModel();
        Model.slider_slider = Document.GetComponent<global::UnityEngine.UI.Slider>("b_Slider");
        Model.text_info = Document.GetComponent<global::TMPro.TextMeshProUGUI>("b_info");
        await m_Controller.OnAwakeAsync(this, Model);
    }

    public override UniTask OnOpenAsync()
    {
        return m_Controller.OnOpenAsync(this);
    }

    public override void OnEnable()
    {
        m_Controller.OnEnable(this);
    }

    public override void OnDisable()
    {
        m_Controller.OnDisable(this);
    }

    public override void Release()
    {
        m_Controller.Release(this);
        Model = null;
        base.Release();
    }
}
