// <auto-generated />
// Toast 飘字窗口绑定（GDK 代码侧）。
// prefab 由客户端提供，路径为客户端 Bundles 下的 UI_Dialog.prefab。
// 客户端 prefab 结构约定（绑定 key）：
//   - UIDocument 组件（必选）
//   - b_temp : RectTransform — 包含 Image 背景和 TMP_Text 文本的条目模板
using Cysharp.Threading.Tasks;
using GameDeveloperKit.UI;

[UIOption("Assets/Bundles/UI/Common/Popup/UI_Dialog.prefab", 400 /* UILayer.Message */)]
public sealed partial class ToastWindow
{
    private global::UnityEngine.RectTransform rect_template;

    private UniTask InitializeDesignAsync()
    {
        rect_template = Document.GetComponent<global::UnityEngine.RectTransform>("b_temp");
        return UniTask.CompletedTask;
    }

    private void ReleaseDesign()
    {
        rect_template = null;
    }
}
