// <auto-generated />
// Toast 飘字窗口绑定（GDK 代码侧）。
// prefab 由客户端提供，路径约定为 Resources/Toast（客户端工程 Assets/Resources/Toast.prefab）。
// 客户端 prefab 结构约定（绑定 key）：
//   - UIDocument 组件（必选）
//   - b_text_content : TextMeshProUGUI — 飘字文本
//   - （可选）CanvasGroup — 根节点上挂载后启用淡入淡出动画
using Cysharp.Threading.Tasks;
using GameDeveloperKit.UI;

[UIOption("Resources/Toast", 400 /* UILayer.Message */)]
public sealed partial class ToastWindow
{
    private global::TMPro.TextMeshProUGUI text_content;

    private UniTask InitializeDesignAsync()
    {
        text_content = Document.GetComponent<global::TMPro.TextMeshProUGUI>("b_text_content");
        return UniTask.CompletedTask;
    }

    private void ReleaseDesign()
    {
        text_content = null;
    }
}
