using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Runtime.ExceptionServices;
using GameDeveloperKit.UI;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.UI;

namespace GameDeveloperKit.Tests
{
    public sealed class UIDocumentGeneratorTests
    {
        private readonly List<UnityEngine.Object> m_CreatedObjects = new List<UnityEngine.Object>();
        private readonly List<string> m_TempFolders = new List<string>();

        [TearDown]
        public void TearDown()
        {
            for (var i = 0; i < m_CreatedObjects.Count; i++)
            {
                UnityEngine.Object.DestroyImmediate(m_CreatedObjects[i]);
            }

            for (var i = 0; i < m_TempFolders.Count; i++)
            {
                if (Directory.Exists(m_TempFolders[i]))
                {
                    Directory.Delete(m_TempFolders[i], true);
                }
            }

            m_CreatedObjects.Clear();
            m_TempFolders.Clear();
        }

        [Test]
        public void Generate_WhenLocalizedTextBindingExists_EmitsRefreshAndSubscription()
        {
            var document = CreateTextDocument(out var text, new[] { "ui.title" });
            var folder = CreateTempFolder();

            InvokeGenerate(document, "Sample", folder);

            var generatedFolder = GetGeneratedFolder(folder);
            var logic = System.IO.File.ReadAllText(Path.Combine(generatedFolder, "SampleWindow.cs"));
            var design = System.IO.File.ReadAllText(Path.Combine(generatedFolder, "SampleWindow.Design.g.cs"));
            var model = System.IO.File.ReadAllText(Path.Combine(generatedFolder, "SampleWindow.Model.g.cs"));

            StringAssert.Contains("public sealed partial class SampleWindow : UIWindow", logic);
            StringAssert.Contains("await InitializeDesignAsync();", logic);
            StringAssert.Contains("ReleaseDesign();", logic);
            StringAssert.Contains("using GameDeveloperKit.Localization;", design);
            StringAssert.Contains("[UIOption(\"Assets/UI/Test.prefab\", UILayer.Window)]", design);
            StringAssert.Contains("private global::UnityEngine.UI.Text text_title;", design);
            StringAssert.Contains("text_title = Document.GetComponent<global::UnityEngine.UI.Text>(\"b_Title\");", design);
            StringAssert.Contains("text_title = null;", design);
            StringAssert.Contains("private bool m_LocalizationSubscribed;", design);
            StringAssert.Contains("App.Localization.LocaleChanged += OnLocaleChanged;", design);
            StringAssert.Contains("private void RefreshLocalization()", design);
            StringAssert.Contains("text_title.text = App.Localization.GetText(\"ui.title\");", design);
            StringAssert.Contains("App.TryGetRegistered<LocalizationModule>(out var localization)", design);
            StringAssert.Contains("public sealed partial class SampleWindow", model);
            StringAssert.Contains("public sealed class Model", model);
            Assert.IsFalse(model.Contains("text_title"), model);
            Assert.IsFalse(model.Contains("global::UnityEngine.UI.Text"), model);
            Assert.IsFalse(System.IO.File.Exists(Path.Combine(generatedFolder, "SampleModule.g.cs")));
            Assert.IsFalse(System.IO.File.Exists(Path.Combine(generatedFolder, "SampleController.cs")));

            Assert.Less(
                design.IndexOf("SubscribeLocalization();", StringComparison.Ordinal),
                design.IndexOf("return UniTask.CompletedTask;", StringComparison.Ordinal));
            Assert.AreSame(text, document.LocalizedTexts[0].Component);
        }

        [Test]
        public void Generate_WhenNoLocalizedTextBindings_DoesNotReferenceLocalization()
        {
            var document = CreateTextDocument(out _, Array.Empty<string>());
            var folder = CreateTempFolder();

            InvokeGenerate(document, "Plain", folder);

            var design = System.IO.File.ReadAllText(Path.Combine(GetGeneratedFolder(folder), "PlainWindow.Design.g.cs"));

            Assert.IsFalse(design.Contains("GameDeveloperKit.Localization"), design);
            Assert.IsFalse(design.Contains("RefreshLocalization"), design);
            Assert.IsFalse(design.Contains("LocaleChanged"), design);
        }

        [Test]
        public void Generate_WhenWindowNameContainsUnderscore_PreservesWindowTypeAndCreatesExpectedFiles()
        {
            var document = CreateTextDocument(out _, Array.Empty<string>());
            var folder = CreateTempFolder();
            System.IO.File.WriteAllText(Path.Combine(folder, "UI_ExampleWindow.Design.g.cs"), "// <auto-generated />\n// old design");
            System.IO.File.WriteAllText(Path.Combine(folder, "UI_ExampleWindow.Design.g.cs.meta"), "old design meta");
            System.IO.File.WriteAllText(Path.Combine(folder, "UI_ExampleWindow.Model.g.cs"), "// <auto-generated />\n// old model");
            System.IO.File.WriteAllText(Path.Combine(folder, "UI_ExampleWindow.Model.g.cs.meta"), "old meta");
            System.IO.File.WriteAllText(Path.Combine(folder, "UIExampleWindow.Model.g.cs"), "// <auto-generated />\n// legacy old model");
            System.IO.File.WriteAllText(Path.Combine(folder, "UIExampleWindow.Model.g.cs.meta"), "legacy old meta");

            InvokeGenerate(document, "UI_ExampleWindow", folder, "Assets/UI/UI_ExampleWindow.prefab");

            var generatedFolder = GetGeneratedFolder(folder, "UI_ExampleWindow");
            Assert.IsTrue(System.IO.File.Exists(Path.Combine(generatedFolder, "UI_ExampleWindow.cs")));
            Assert.IsTrue(System.IO.File.Exists(Path.Combine(generatedFolder, "UI_ExampleWindow.Design.g.cs")));
            Assert.IsTrue(System.IO.File.Exists(Path.Combine(generatedFolder, "UI_ExampleWindow.Model.g.cs")));
            Assert.IsFalse(System.IO.File.Exists(Path.Combine(folder, "UI_ExampleWindow.Design.g.cs")));
            Assert.IsFalse(System.IO.File.Exists(Path.Combine(folder, "UI_ExampleWindow.Design.g.cs.meta")));
            Assert.IsFalse(System.IO.File.Exists(Path.Combine(folder, "UI_ExampleWindow.Model.g.cs")));
            Assert.IsFalse(System.IO.File.Exists(Path.Combine(folder, "UI_ExampleWindow.Model.g.cs.meta")));
            Assert.IsFalse(System.IO.File.Exists(Path.Combine(folder, "UIExampleWindow.Model.g.cs")));
            Assert.IsFalse(System.IO.File.Exists(Path.Combine(folder, "UIExampleWindow.Model.g.cs.meta")));

            var logic = System.IO.File.ReadAllText(Path.Combine(generatedFolder, "UI_ExampleWindow.cs"));
            var design = System.IO.File.ReadAllText(Path.Combine(generatedFolder, "UI_ExampleWindow.Design.g.cs"));
            var model = System.IO.File.ReadAllText(Path.Combine(generatedFolder, "UI_ExampleWindow.Model.g.cs"));

            StringAssert.Contains("public sealed partial class UI_ExampleWindow : UIWindow", logic);
            StringAssert.Contains("public sealed partial class UI_ExampleWindow", design);
            StringAssert.Contains("public sealed partial class UI_ExampleWindow", model);
            StringAssert.Contains("public sealed class Model", model);
            Assert.IsFalse(model.Contains("// old model"), model);
            Assert.IsFalse(model.Contains("text_title"), model);
        }

        [Test]
        public void Generate_WhenLogicFileExists_DoesNotOverwriteUserCode()
        {
            var document = CreateTextDocument(out _, Array.Empty<string>());
            var folder = CreateTempFolder();
            var logicPath = Path.Combine(folder, "SampleWindow.cs");
            System.IO.File.WriteAllText(logicPath, "// user code");

            InvokeGenerate(document, "Sample", folder);

            Assert.AreEqual("// user code", System.IO.File.ReadAllText(logicPath));
            var generatedFolder = GetGeneratedFolder(folder);
            Assert.IsFalse(System.IO.File.Exists(Path.Combine(generatedFolder, "SampleWindow.cs")));
            Assert.IsTrue(System.IO.File.Exists(Path.Combine(generatedFolder, "SampleWindow.Design.g.cs")));
            Assert.IsTrue(System.IO.File.Exists(Path.Combine(generatedFolder, "SampleWindow.Model.g.cs")));
        }

        [Test]
        public void Generate_WhenClassNameIsNotIdentifier_ConvertsToValidWindowType()
        {
            var document = CreateTextDocument(out _, Array.Empty<string>());
            var folder = CreateTempFolder();

            InvokeGenerate(document, "sample-window", folder);

            var generatedFolder = GetGeneratedFolder(folder);
            Assert.IsTrue(System.IO.File.Exists(Path.Combine(generatedFolder, "SampleWindow.cs")));
            Assert.IsTrue(System.IO.File.Exists(Path.Combine(generatedFolder, "SampleWindow.Design.g.cs")));
            Assert.IsTrue(System.IO.File.Exists(Path.Combine(generatedFolder, "SampleWindow.Model.g.cs")));
        }

        [Test]
        public void Generate_WhenDuplicateFieldNameExists_Throws()
        {
            var document = CreateDuplicateFieldDocument();
            var folder = CreateTempFolder();

            var exception = Assert.Throws<GameException>(() => InvokeGenerate(document, "Broken", folder));

            StringAssert.Contains("Duplicate UI binding field name", exception.Message);
        }

        [Test]
        public void Generate_WhenLocalizedTextKeyIsEmpty_Throws()
        {
            var document = CreateTextDocument(out _, new[] { " " });
            var folder = CreateTempFolder();

            var exception = Assert.Throws<GameException>(() => InvokeGenerate(document, "Broken", folder));

            StringAssert.Contains("key cannot be empty", exception.Message);
        }

        [Test]
        public void Generate_WhenLocalizedComponentIsNotSelected_Throws()
        {
            var document = CreateTextDocument(out var text, Array.Empty<string>());
            SetDocumentData(document, new[]
            {
                new UIBindMapping
                {
                    Name = "b_Title",
                    Target = text.gameObject,
                    Components = Array.Empty<Component>()
                }
            }, new[]
            {
                new UILocalizedTextBinding
                {
                    Component = text,
                    Key = "ui.title"
                }
            });
            var folder = CreateTempFolder();

            var exception = Assert.Throws<GameException>(() => InvokeGenerate(document, "Broken", folder));

            StringAssert.Contains("not selected in UI binding", exception.Message);
        }

        [Test]
        public void Generate_WhenLocalizedComponentIsNotText_Throws()
        {
            var document = CreateImageDocument(out var image);
            var folder = CreateTempFolder();

            var exception = Assert.Throws<GameException>(() => InvokeGenerate(document, "Broken", folder));

            StringAssert.Contains("type is not supported", exception.Message);
            StringAssert.Contains("Image", exception.Message);
        }

        [Test]
        public void Generate_WhenLocalizedComponentIsDuplicated_Throws()
        {
            var document = CreateTextDocument(out var text, new[] { "ui.title" });
            SetDocumentData(document, new[]
            {
                new UIBindMapping
                {
                    Name = "b_Title",
                    Target = text.gameObject,
                    Components = new Component[] { text }
                }
            }, new[]
            {
                new UILocalizedTextBinding
                {
                    Component = text,
                    Key = "ui.title"
                },
                new UILocalizedTextBinding
                {
                    Component = text,
                    Key = "ui.title.other"
                }
            });
            var folder = CreateTempFolder();

            var exception = Assert.Throws<GameException>(() => InvokeGenerate(document, "Broken", folder));

            StringAssert.Contains("Duplicate UI localized text binding", exception.Message);
        }

        private UIDocument CreateTextDocument(out Text text, string[] keys)
        {
            var document = CreateDocument("b_Title");
            text = document.transform.GetChild(0).gameObject.AddComponent<Text>();
            var localizedTexts = new UILocalizedTextBinding[keys.Length];
            for (var i = 0; i < keys.Length; i++)
            {
                localizedTexts[i] = new UILocalizedTextBinding
                {
                    Component = text,
                    Key = keys[i]
                };
            }

            SetDocumentData(document, new[]
            {
                new UIBindMapping
                {
                    Name = "b_Title",
                    Target = text.gameObject,
                    Components = new Component[] { text }
                }
            }, localizedTexts);
            return document;
        }

        private UIDocument CreateImageDocument(out Image image)
        {
            var document = CreateDocument("b_Icon");
            image = document.transform.GetChild(0).gameObject.AddComponent<Image>();
            SetDocumentData(document, new[]
            {
                new UIBindMapping
                {
                    Name = "b_Icon",
                    Target = image.gameObject,
                    Components = new Component[] { image }
                }
            }, new[]
            {
                new UILocalizedTextBinding
                {
                    Component = image,
                    Key = "ui.icon"
                }
            });
            return document;
        }

        private UIDocument CreateDuplicateFieldDocument()
        {
            var root = new GameObject("Document");
            var first = new GameObject("b_Title");
            var second = new GameObject("Title");
            first.transform.SetParent(root.transform, false);
            second.transform.SetParent(root.transform, false);
            m_CreatedObjects.Add(root);

            var firstText = first.AddComponent<Text>();
            var secondText = second.AddComponent<Text>();
            var document = root.AddComponent<UIDocument>();
            SetDocumentData(document, new[]
            {
                new UIBindMapping
                {
                    Name = "b_Title",
                    Target = first,
                    Components = new Component[] { firstText }
                },
                new UIBindMapping
                {
                    Name = "Title",
                    Target = second,
                    Components = new Component[] { secondText }
                }
            }, Array.Empty<UILocalizedTextBinding>());
            return document;
        }

        private UIDocument CreateDocument(string childName)
        {
            var root = new GameObject("Document");
            var child = new GameObject(childName);
            child.transform.SetParent(root.transform, false);
            m_CreatedObjects.Add(root);
            return root.AddComponent<UIDocument>();
        }

        private static void SetDocumentData(UIDocument document, UIBindMapping[] mappings, UILocalizedTextBinding[] localizedTexts)
        {
            SetPrivateField(document, "mappings", mappings);
            SetPrivateField(document, "localizedTexts", localizedTexts);
        }

        private static void SetPrivateField(UIDocument document, string fieldName, object value)
        {
            var field = typeof(UIDocument).GetField(fieldName, BindingFlags.Instance | BindingFlags.NonPublic);
            Assert.IsNotNull(field, fieldName);
            field.SetValue(document, value);
        }

        private string CreateTempFolder()
        {
            var folder = Path.Combine(Path.GetTempPath(), "uidocument-generator-tests-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(folder);
            m_TempFolders.Add(folder);
            return folder;
        }

        private static string GetGeneratedFolder(string folder, string prefabName = "Test")
        {
            return Path.Combine(folder, prefabName);
        }

        private static void InvokeGenerate(UIDocument document, string className, string folder, string uiPath = "Assets/UI/Test.prefab")
        {
            var generatorType = Type.GetType("GameDeveloperKit.UIEditor.UIDocumentGenerator, GameDeveloperKit.Editor", true);
            var generate = generatorType.GetMethod("Generate", BindingFlags.Public | BindingFlags.Static);
            Assert.IsNotNull(generate);
            try
            {
                generate.Invoke(null, new object[] { document, className, folder, uiPath, UILayer.Window });
            }
            catch (TargetInvocationException exception) when (exception.InnerException != null)
            {
                ExceptionDispatchInfo.Capture(exception.InnerException).Throw();
            }
        }
    }
}
