// <auto-generated />
using Cysharp.Threading.Tasks;
using GameDeveloperKit.UI;

[UIOption("Assets/GameDeveloperKit/Simples/UI/Loading.prefab", 200)]
public sealed partial class LoadingWindow
{
    private global::UnityEngine.UI.Slider slider_slider;
    private global::TMPro.TextMeshProUGUI text_info;

    private UniTask InitializeDesignAsync()
    {
        slider_slider = Document.GetComponent<global::UnityEngine.UI.Slider>("b_Slider");
        text_info = Document.GetComponent<global::TMPro.TextMeshProUGUI>("b_info");
        return UniTask.CompletedTask;
    }

    private void ReleaseDesign()
    {
        slider_slider = null;
        text_info = null;
    }
}
